//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McDrWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mcdrEntities : DbContext
    {
        public mcdrEntities()
            : base("name=mcdrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cita> citas { get; set; }
        public virtual DbSet<especialidad> especialidads { get; set; }
        public virtual DbSet<medico> medicos { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
    }
}
